# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPostales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('calle', models.CharField(max_length=250)),
                ('numero_exterior', models.CharField(max_length=250)),
                ('numero_interior', models.CharField(max_length=250)),
                ('colonia', models.CharField(max_length=250)),
                ('c_p', models.IntegerField()),
                ('delegacion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
            ],
        ),
    ]
