# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPostales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=200)),
                ('calle', models.CharField(max_length=250)),
                ('numero_exterior', models.CharField(max_length=250)),
                ('numero_interior', models.CharField(max_length=250)),
                ('colonia', models.CharField(max_length=250)),
                ('c_p', models.IntegerField()),
                ('delegacion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud_origen', models.FloatField()),
                ('longitud_origen', models.FloatField()),
                ('latitud_destino', models.FloatField()),
                ('longitud_destino', models.FloatField()),
                ('precio', models.FloatField(default=0)),
                ('detalles', models.TextField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cliente')),
                ('mensajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Mensajero')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mensajero',
            unique_together=set([('nombre', 'telefono')]),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set([('nombre', 'email', 'telefono')]),
        ),
    ]
