# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161210_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='longitud',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospostales',
            name='email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospostales',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='latitud_destino',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='latitud_origen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='longitud_destino',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='longitud_origen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together=set([('nombre', 'email', 'telefono')]),
        ),
        migrations.AlterUniqueTogether(
            name='mensajero',
            unique_together=set([('nombre', 'telefono')]),
        ),
    ]
